# Carregar biblioteca externas

In [121]:
import sys
import os
import numpy as np
from dataclasses import asdict
import pandas as pd

sys.path.append(os.path.abspath(".."))

# Carregamento modulos

In [122]:
from src.data.loan_loader import load_csv
from src.preprocessing.transform import clean_dataset, split_data, build_feature_matrix

# Carregamento do dataset

In [123]:
loaded = load_csv('../data/loan_data.csv')

In [124]:
loaded_view = pd.DataFrame([asdict(record) for record in loaded])
display(loaded_view)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

# Transformação

In [125]:
cleaned = clean_dataset(loaded)
cleaned_view = pd.DataFrame([asdict(record) for record in cleaned])
display(cleaned_view)

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,gender_female,education_level,home_ownership,loan_intent,previous_default,loan_status
0,22.0,71948.0,0,35000.0,16.02,0.49,3.0,561,1,3,RENT,PERSONAL,0,1
1,21.0,12282.0,0,1000.0,11.14,0.08,2.0,504,1,0,OWN,EDUCATION,1,0
2,25.0,12438.0,3,5500.0,12.87,0.44,3.0,635,1,0,MORTGAGE,MEDICAL,0,1
3,23.0,79753.0,0,35000.0,15.23,0.44,2.0,675,1,2,RENT,MEDICAL,0,1
4,24.0,66135.0,1,35000.0,14.27,0.53,4.0,586,0,3,RENT,MEDICAL,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,47971.0,6,15000.0,15.66,0.31,3.0,645,0,1,RENT,MEDICAL,0,1
44996,37.0,65800.0,17,9000.0,14.07,0.14,11.0,621,1,1,RENT,HOMEIMPROVEMENT,0,1
44997,33.0,56942.0,7,2771.0,10.02,0.05,10.0,668,0,1,RENT,DEBTCONSOLIDATION,0,1
44998,29.0,33164.0,4,12000.0,13.23,0.36,6.0,604,0,2,RENT,EDUCATION,0,1
44999,24.0,51609.0,1,6665.0,17.05,0.13,3.0,628,0,0,RENT,DEBTCONSOLIDATION,0,1

In [126]:
features, target, names = build_feature_matrix(cleaned)
features_view = pd.DataFrame(features, columns=names)
display(features_view)

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,gender_female,education_level,...,home_ownership=MORTGAGE,home_ownership=OTHER,home_ownership=OWN,home_ownership=RENT,loan_intent=DEBTCONSOLIDATION,loan_intent=EDUCATION,loan_intent=HOMEIMPROVEMENT,loan_intent=MEDICAL,loan_intent=PERSONAL,loan_intent=VENTURE
0,22.0,71948.0,0.0,35000.0,16.02,0.49,3.0,561.0,1.0,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,21.0,12282.0,0.0,1000.0,11.14,0.08,2.0,504.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,25.0,12438.0,3.0,5500.0,12.87,0.44,3.0,635.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,23.0,79753.0,0.0,35000.0,15.23,0.44,2.0,675.0,1.0,2.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,24.0,66135.0,1.0,35000.0,14.27,0.53,4.0,586.0,0.0,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,47971.0,6.0,15000.0,15.66,0.31,3.0,645.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
44996,37.0,65800.0,17.0,9000.0,14.07,0.14,11.0,621.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
44997,33.0,56942.0,7.0,2771.0,10.02,0.05,10.0,668.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
44998,29.0,33164.0,4.0,12000.0,13.23,0.36,6.0,604.0,0.0,2.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
44999,24.0,51609.0,1.0,6665.0,17.05,0.13,3.0,628.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

# Divisão de dataset para treinamento e teste

In [127]:
train, test = split_data(features)

# Dados para treinamento

In [128]:
train_view = pd.DataFrame(train, columns=names)
display(train_view)

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,gender_female,education_level,...,home_ownership=MORTGAGE,home_ownership=OTHER,home_ownership=OWN,home_ownership=RENT,loan_intent=DEBTCONSOLIDATION,loan_intent=EDUCATION,loan_intent=HOMEIMPROVEMENT,loan_intent=MEDICAL,loan_intent=PERSONAL,loan_intent=VENTURE
0,35.0,180779.0,13.0,10000.0,7.90,0.06,9.0,714.0,1.0,4.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,25.0,87180.0,1.0,25000.0,11.81,0.29,3.0,549.0,0.0,2.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,21.0,99466.0,0.0,12000.0,15.21,0.12,4.0,614.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,22.0,85115.0,1.0,13000.0,11.14,0.15,2.0,650.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,25.0,24035.0,0.0,5000.0,9.62,0.21,2.0,530.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,21.0,78529.0,2.0,15000.0,11.83,0.19,2.0,687.0,0.0,2.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
35996,22.0,65866.0,4.0,7000.0,13.47,0.11,2.0,697.0,0.0,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
35997,26.0,30278.0,3.0,6000.0,6.62,0.20,4.0,628.0,0.0,2.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
35998,33.0,87097.0,12.0,2931.0,10.35,0.03,12.0,642.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
35999,28.0,138960.0,4.0,18000.0,10.37,0.13,7.0,733.0,1.0,2.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

# Dados para testes

In [129]:
test_view = pd.DataFrame(test, columns=names)
display(test_view)

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,gender_female,education_level,...,home_ownership=MORTGAGE,home_ownership=OTHER,home_ownership=OWN,home_ownership=RENT,loan_intent=DEBTCONSOLIDATION,loan_intent=EDUCATION,loan_intent=HOMEIMPROVEMENT,loan_intent=MEDICAL,loan_intent=PERSONAL,loan_intent=VENTURE
0,28.0,72681.0,6.0,4500.0,14.21,0.06,9.0,704.0,0.0,2.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,41.0,84821.0,19.0,5000.0,12.69,0.06,12.0,695.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,36.0,48269.0,14.0,5000.0,5.79,0.10,16.0,691.0,0.0,2.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,25.0,76833.0,5.0,1500.0,7.49,0.02,2.0,656.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,27.0,61144.0,1.0,15000.0,10.42,0.25,5.0,653.0,0.0,2.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,30.0,84856.0,4.0,4514.0,5.96,0.05,9.0,686.0,0.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8996,25.0,41912.0,5.0,5000.0,9.38,0.12,3.0,663.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
8997,26.0,126173.0,4.0,5000.0,7.88,0.04,3.0,668.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
8998,29.0,45178.0,8.0,6500.0,11.01,0.14,8.0,595.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
8999,24.0,78831.0,3.0,7200.0,17.58,0.09,4.0,574.0,0.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0